version: "3"
services:
  api-nodejs:
    restart: always
    build: .
    ports:
      - 3001:3001
    env_file: .env
    environment:
      - NODE_ENV=docker
      - DB_HOST=mongo
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"